### Get all dogs
GET localhost:5500/dashboard/animals/dogs
Accept: application/json

### Get dogs by id
GET localhost:5500/dashboard/animals/dogs/65602055473d223cb10f6972
Accept: application/json

### Create dog
POST localhost:5500/dashboard/animals/dogs
Content-Type: application/json

{
  "intelligence": "Medium",
  "shedding_level": "High",
  "exercise_needs": "Moderate",
  "breed": "Labrador Retriever",
  "size": "Large",
  "temperament": "Outgoing",
  "life_span": "10-14 years",
  "origin": "Canada",
  "color": "Yellow"
}

### Update dog
PUT localhost:5500/dashboard/animals/dogs/65602055473d223cb10f6972
Content-Type: application/json

{
  "intelligence": "DELETE",
  "shedding_level": "Moderate",
  "exercise_needs": "Moderate",
  "breed": "German Shepherd",
  "size": "Large",
  "temperament": "Loyal",
  "life_span": "10-12 years",
  "origin": "Germany",
  "color": "Black and Tan"
}

### Delete dog
DELETE localhost:5500/dashboard/animals/dogs/65602055473d223cb10f6972
Accept: application/json