### GET all dogs
GET localhost:8080/dogs
Content-Type: application/json

### GET dog from id
GET localhost:8080/dogs/655525e0ab65c84ca31fd0fa
Content-Type: application/json

### Add dog
POST localhost:8080/dogs
Content-Type: application/json

{
  "breed": "Shrek's Donkey",
  "size": "Large",
  "temperament": [
    "Friendly",
    "Outgoing",
    "Even Tempered"
  ],
  "life_span": "10-12 years",
  "origin": "United Kingdom",
  "color": [
    "Black",
    "Yellow",
    "Chocolate"
  ],
  "characteristics": {
    "intelligence": "High",
    "shedding_level": "Moderate",
    "exercise_needs": "High"
  }
}

### PUT (Update) dog using id
PUT localhost:8080/dogs/6555835b196df62d8630a3c6
Content-Type: application/json

{
  "breed": "DONKEYYYY DOOOONKEEEY",
  "size": "Large",
  "temperament": [
    "Friendly",
    "Outgoing",
    "Even Tempered"
  ],
  "life_span": "10-12 years",
  "origin": "United Kingdom",
  "color": [
    "Black",
    "Yellow",
    "Chocolate"
  ],
  "characteristics": {
    "intelligence": "High",
    "shedding_level": "Moderate",
    "exercise_needs": "High"
  }
}

### PATCH (Update) dog using id
PATCH localhost:8080/dogs/6555835b196df62d8630a3c6
Content-Type: application/json

{
  "breed": "Shrek DOENDOENDOEDN",
  "size": "Large",
  "temperament": [
    "Friendly",
    "Outgoing",
    "Even Tempered"
  ],
  "life_span": "10-12 years",
  "origin": "United Kingdom",
  "color": [
    "Black",
    "Yellow",
    "Chocolate"
  ],
  "characteristics": {
    "intelligence": "High",
    "shedding_level": "Moderate",
    "exercise_needs": "High"
  }
}

### DELETE dog from id
DELETE localhost:8080/dogs/6555902e7de170a7e017ade6
Content-Type: application/json