### GET all users
GET localhost:8080/users
Content-Type: application/json

### GET user from id
GET localhost:8080/users/65412b9102c401c81734d692
Content-Type: application/json

### POST user
POST localhost:8080/users
Content-Type: application/json

{
	"birthday": "1999-10-10",
	"email": "plankton@example.com",
	"favoriteColor": "White",
	"firstName": "Chum",
	"lastName": "Bucket"
}

### DELETE user from id
DELETE localhost:8080/users/6541a9a494d0b427d080998d
Content-Type: application/json