### GET request to users
GET localhost:8080/users
Content-Type: application/json

### GET request to user/:id
GET localhost:8080/users/65412b9102c401c81734d692
Content-Type: application/json

### POST request to users
POST localhost:8080/users
Content-Type: application/json

{
	"birthday": "2010-02-02",
	"email": "fakeemail@gmail.com",
	"firstName": "Isabel"
}