### GET request to users route
GET localhost:8080/users
Content-Type: application/json

### POST request to users route
POST localhost:8080/users
Content-Type: application/json

{
  	"firstName": "Abraham",
	"lastName": "Jimenez",
	"email": "email@email.com",
	"favoriteColor": "white",
	"birthday": "2000-01-01"
}