openapi: 3.0.3
info:
  title: Contacts API
  description: Contacts API is used to get information of contacts
  version: 0.1.9
servers:
  - url: http://localhost:8080/
    description: Local development server
  - url: https://cse341-r5ip.onrender.com
    description: Production server
paths:
  /users:
    get:
      tags:
        - Get
      description: Returns a list of users.
      responses:
        200:
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    post:
      tags:
        - Post
      description: Add a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                favoriteColor:
                  type: string
                birthday:
                  type: string
                  format: date
      responses:
        201:
          description: User created successfully
        400:
          description: Bad Request. Invalid data provided
  /users/{userId}:
    get:
      tags:
        - Get
      description: Get a user by id.
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: The unique ID of the user
      responses:
        200:
          description: The unique ID of the user
          content:
            application/json:
              schema:
                type: object
    patch:
      tags:
        - Patch
      description: Update a user by id
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: The unique ID of the user
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                favoriteColor:
                  type: string
                birthday:
                  type: string
                  format: date
      responses:
        200:
          description: User updated successfully
        400:
          description: Bad request. Invalid data provided
    delete:
      tags:
        - Delete
      description: Delete a user by id
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: The unique ID of the user
      responses:
        204:
          description: deleted successfully
        400:
          description: request. Invalid data provided