### GET all horses
GET localhost:8080/horses
Content-Type: application/json

### GET horse from id
GET localhost:8080/horses/655525e0ab65c84ca31fd0f4
Content-Type: application/json

### Add horse
POST localhost:8080/horses
Content-Type: application/json

{
  "breed": "TEST",
  "size": "Small",
  "temperament": [
    "Energetic",
    "Intelligent",
    "Strong-willed"
  ],
  "life_span": "20-30 years",
  "origin": "United Kingdom",
  "color": [
    "Any color"
  ],
  "characteristics": {
    "size": "Tiny",
    "endurance": "Moderate",
    "height": "Up to 10.2 hands"
  }
}

### PUT (Update) horse using id
PUT localhost:8080/horses/6541b05a240790ea94794333
Content-Type: application/json

{
  "breed": "TEST PUT",
  "size": "Small",
  "temperament": [
    "Energetic",
    "Intelligent",
    "Strong-willed"
  ],
  "life_span": "20-30 years",
  "origin": "United Kingdom",
  "color": [
    "Any color"
  ],
  "characteristics": {
    "size": "Tiny",
    "endurance": "Moderate",
    "height": "Up to 10.2 hands"
  }
}

### PATCH (Update) horse using id
PATCH localhost:8080/horses/6541b05a240790ea94794333
Content-Type: application/json

{
  "breed": "TEST PATCH",
  "size": "Small",
  "temperament": [
    "Energetic",
    "Intelligent",
    "Strong-willed"
  ],
  "life_span": "20-30 years",
  "origin": "United Kingdom",
  "color": [
    "Any color"
  ],
  "characteristics": {
    "size": "Tiny",
    "endurance": "Moderate",
    "height": "Up to 10.2 hands"
  }
}

### DELETE horse from id
DELETE localhost:8080/horses/65552628ab65c84ca32045b3
Content-Type: application/json